version: '3.8' # Define a versão do docker-compose

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_container # Nome do container (opcional)
    restart: always
    environment:
      POSTGRES_USER: sevenbikes # Nome de usuário do PostgreSQL
      POSTGRES_PASSWORD: sevenbikes # Senha de usuário
      POSTGRES_DB: register # Nome do banco de dados
    ports:
      - "6543:5432" # Mapeia a porta local para o container
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volume para persistir os dados

volumes:
  postgres_data: